// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGQCPdR6uwErCe9L7BMKuKHGPRkGrYd0o',
    appId: '1:28189343074:web:f6b3aabe0848699bb9c03b',
    messagingSenderId: '28189343074',
    projectId: 'jade-dev-1e742',
    authDomain: 'jade-dev-1e742.firebaseapp.com',
    storageBucket: 'jade-dev-1e742.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa87O4oSFGTj2DPBnW0nn-TLa4lCYrQG8',
    appId: '1:28189343074:android:3830ac9f5ac7445cb9c03b',
    messagingSenderId: '28189343074',
    projectId: 'jade-dev-1e742',
    storageBucket: 'jade-dev-1e742.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbXV27ccHoSJHYOWtjbgZbn0-4EInTJeU',
    appId: '1:28189343074:ios:029da12482fb5963b9c03b',
    messagingSenderId: '28189343074',
    projectId: 'jade-dev-1e742',
    storageBucket: 'jade-dev-1e742.appspot.com',
    iosClientId: '28189343074-k0rttnmllnnhj7hudnvp4roijohbps8g.apps.googleusercontent.com',
    iosBundleId: 'com.jadeapp.jade',
  );
}
